[package]
name = "buffers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test_utils = { path = "../a_test_utils" }
static_assertions = "1.1.0"
